backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "main"
    label: "main" 
    folder: "content/posts/main"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "altcoins"
    label: "Alt Coins" 
    folder: "content/posts/altcoins"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}